language: node_js
dist: trusty
node_js:
- '10'
- '8'
- '6'
matrix:
  allow_failures:
    - node_js: '10'
addons:
  postgresql: "9.6"
services:
- mysql
- postgresql
env:
- MYSQL_PORT=3306 POSTGRESQL_PORT=5432
before_install:
- mkdir -p $HOME/.local/flywaybin
- wget -O- 'https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.0.7/flyway-commandline-5.0.7-linux-x64.tar.gz' | tar xz -C $HOME/.local/flywaybin
- ln -s flyway-5.0.7 $HOME/.local/flywaybin/latest
- sudo pip install -U urllib3 requests
- sudo pip install futoin-cid
- sudo bash test/db_config.sh
script:
- rm -rf node_modules
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid prepare
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid run test

